# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20171117_1211'),
        ('viewer', '0002_auto_20171117_1216'),
    ]

    operations = [
    ]
